# Generated by Django 4.2.1 on 2023-06-12 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='label',
        ),
    ]
